email: erinbesseau@gmail.com
instagram: https://www.instagram.com/erinbesseau.art/
facebook: https://www.facebook.com/erinbesseau.a
twitter: https://twitter.com/ErinBesseau
home:
  title: Erin Besseau
  subtitle: Erin Besseau is a multimedia visual artist focusing on transient forms and motifs.
  content: "Besseau heralds from a small town outside of Ottawa Ontario and uses experiences growing up in the countryside to create imagery that discusses transformation, nostalgia and growth.<br><br>Focusing heavily on the way mental health impacts her day to day life, Besseau uses her art to create a feeling of safety and catharsis that is amplified by the soft blue tones in her most recent body of work. Besseau is a 2017 alumnus of the Nova Scotia College of Art and Design University."
  galleryTitle: Recent work